# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pmg < Formula
  desc "PMG protects developers from malicious packages"
  homepage "https://github.com/safedep/pmg"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/safedep/pmg/releases/download/v0.14.0/pmg_Darwin_all.tar.gz"
    sha256 "518d7caed79ffb9044361a1ee94fe9847dd8f7d96b017a65a77f751118fab8e0"

    define_method(:install) do
      bin.install "pmg"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/safedep/pmg/releases/download/v0.14.0/pmg_Linux_x86_64.tar.gz"
      sha256 "8ccec24fe55e2b0bfd37b7fcf2b9060ca1a73535e0d6244ffbb820cfb918536c"
      define_method(:install) do
        bin.install "pmg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/safedep/pmg/releases/download/v0.14.0/pmg_Linux_arm64.tar.gz"
      sha256 "5c192047cbf02256ca3fc59109e76054f36ba9b456e5d7ae86c8824cab419ccb"
      define_method(:install) do
        bin.install "pmg"
      end
    end
  end
end
