# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pmg < Formula
  desc "PMG protects developers from malicious packages"
  homepage "https://github.com/safedep/pmg"
  version "0.3.3"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/safedep/pmg/releases/download/v0.3.3/pmg_Darwin_all.tar.gz"
    sha256 "38810f4a2606ea46445464a6cd53ea4b76064dd2de6e827135efdf165da58d52"

    def install
      bin.install "pmg"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/safedep/pmg/releases/download/v0.3.3/pmg_Linux_x86_64.tar.gz"
      sha256 "003461a1e2e7db77e32b9d94c40bef128015efca47fd96b1206d6f82d298e67e"
      def install
        bin.install "pmg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/safedep/pmg/releases/download/v0.3.3/pmg_Linux_arm64.tar.gz"
      sha256 "e40306c9f99bcd96bd5a8a47b5dbd2716d4ede8e78277e0b9edf141839cfbb6f"
      def install
        bin.install "pmg"
      end
    end
  end
end
