# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safedep < Formula
  desc "The SafeDep Platform CLI"
  homepage "https://github.com/safedep/cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/safedep/cli/releases/download/v0.1.0/cli_Darwin_all.tar.gz"
    sha256 "af5714abdc234ff1a7b41f38c0253d201a633c2b7883df80fed0f1e86e331b22"

    define_method(:install) do
      bin.install "cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/safedep/cli/releases/download/v0.1.0/cli_Linux_x86_64.tar.gz"
      sha256 "51d8b6b3436e9824096dc75d7381b76dbdd173b6a6e2f93c1321d2f28a873232"
      define_method(:install) do
        bin.install "safedep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/safedep/cli/releases/download/v0.1.0/cli_Linux_arm64.tar.gz"
      sha256 "8a4492e3655a9ea615a23d58648c9c4f8f2a60881b0c5b2bb040cbb87e11e2ef"
      define_method(:install) do
        bin.install "safedep"
      end
    end
  end
end
