# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vet < Formula
  desc "SafeDep vet is a tool for identifying open source software supply chain risks"
  homepage "https://safedep.io"
  version "1.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/safedep/vet/releases/download/v1.9.0/vet_Darwin_x86_64.tar.gz"
      sha256 "78f8cf7de0cfb96f090d5dcdc270679079d9feea1826852da3b286a17a86ea95"

      def install
        bin.install "vet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/safedep/vet/releases/download/v1.9.0/vet_Darwin_arm64.tar.gz"
      sha256 "ed8e722e12625745ebc7d159d52f8357066a117c38a90605ddb45b1e8c312921"

      def install
        bin.install "vet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/safedep/vet/releases/download/v1.9.0/vet_Linux_x86_64.tar.gz"
        sha256 "86897225691c2b92f2fb5f87f0863b0281369985d74110e1a3ebc9ad5e3bfab5"

        def install
          bin.install "vet"
        end
      end
    end
  end
end
