# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xbom < Formula
  desc "Generate BOMs enriched with AI, SaaS and more using Static Code Analysis"
  homepage "https://github.com/safedep/xbom"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/safedep/xbom/releases/download/v0.0.2/xbom_Darwin_x86_64.tar.gz"
      sha256 "fdd899b7dd11279df231b343fb799b2cc77e4d67b0bf066ddac8541e536faa7e"

      def install
        bin.install "xbom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/safedep/xbom/releases/download/v0.0.2/xbom_Darwin_arm64.tar.gz"
      sha256 "0c5c3ecf2ea45209fed58069784733d7b2ee7042a84e36c9de2ed504cb2021d2"

      def install
        bin.install "xbom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/safedep/xbom/releases/download/v0.0.2/xbom_Linux_x86_64.tar.gz"
      sha256 "6862bf923844313a7b228ae2a0ba431e42b8a0407d3580c031b2cd28fd992b6d"
      def install
        bin.install "xbom"
      end
    end
  end
end
