# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xbom < Formula
  desc "Generate BOMs enriched with AI, SaaS and more using Static Code Analysis"
  homepage "https://github.com/safedep/xbom"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/safedep/xbom/releases/download/v0.0.1/xbom_Darwin_x86_64.tar.gz"
      sha256 "00c110570804d775cf4e19ed824f66b96a7f10bcccd88e1b488e20f2683c9964"

      def install
        bin.install "xbom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/safedep/xbom/releases/download/v0.0.1/xbom_Darwin_arm64.tar.gz"
      sha256 "044f627b19b28742351ad97050d2f2c8dc780f988e6f810428e55dd0dfa4dadd"

      def install
        bin.install "xbom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/safedep/xbom/releases/download/v0.0.1/xbom_Linux_x86_64.tar.gz"
      sha256 "1a4c1eadf42716e1de3f42895073eaa946c8e361c3df182727b803e2989e9b30"
      def install
        bin.install "xbom"
      end
    end
  end
end
