# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.1.4"

  on_macos do
    sha256 "873af84b8119cd0ad9d8412a80312a7cf1586b3a0d080d59a8ee26c691b19dc0"
    url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Darwin_all.tar.gz",
        verified: "github.com/safedep/cli"
  end

  on_linux do
    on_intel do
      sha256 "44a138ccf67873df0cd999ff9d413a00808745758930ed7f3920749b99c296c0"
      url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/cli"
    end
    on_arm do
      sha256 "491476ac18a40710831c967ec17d27ea17c1bf4872878a7a3a5b61b00ac850f8"
      url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz",
        verified: "github.com/safedep/cli"
    end
  end

  name "cli"
  desc "The SafeDep Platform CLI"
  homepage "https://github.com/safedep/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safedep"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/safedep"]
    end
  end

  # No zap stanza required

end
