# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.7.0"

  on_macos do
    sha256 "6b64d484270c8a07917f6aef881e64f69300b0f199e95190f683dd64e82fca46"
    url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Darwin_all.tar.gz",
        verified: "github.com/safedep/cli"
  end
  on_linux do
    on_arm do
      sha256 "d6ced602413d7ca948d22728afc80fcb99792d15efc38e58ef1780d47f95314f"
      url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz",
        verified: "github.com/safedep/cli"
    end
    on_intel do
      sha256 "a726b73c27c020a4ee140aeec77d8231ab719e2f2818098e0747b258d2eb1cf5"
      url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/cli"
    end
  end

  name "cli"
  desc "The SafeDep Platform CLI"
  homepage "https://github.com/safedep/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safedep"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/safedep"]
    end
  end

  # No zap stanza required
end
