# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.1.5"

  on_macos do
    sha256 "70201928062a64088bb85406d057d3df59f1bc680577d6be1be148f072b4a434"
    url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Darwin_all.tar.gz",
        verified: "github.com/safedep/cli"
  end

  on_linux do
    on_intel do
      sha256 "6b42a532a25f95913c2765c30ffd5eb065c07e1b6b992d40f670e5d56470c7e1"
      url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/cli"
    end
    on_arm do
      sha256 "59ab3a51bc52a5bf442567a546b9ab5d3061f71c03f0b6393b25439b72dd7bcf"
      url "https://github.com/safedep/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz",
        verified: "github.com/safedep/cli"
    end
  end

  name "cli"
  desc "The SafeDep Platform CLI"
  homepage "https://github.com/safedep/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safedep"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/safedep"]
    end
  end

  # No zap stanza required

end
