# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmg" do
  version "0.18.0"

  on_macos do
    sha256 "a1f1de3b13fce02a6df40ba2475d946b54f6ae8eb0af2614e26b99691376ded8"
    url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Darwin_all.tar.gz",
        verified: "github.com/safedep/pmg"
  end

  on_linux do
    on_intel do
      sha256 "b756c4e55bd8d50f84f0c9d4faaca82446205fc90ac2056270acbbaae913c0b5"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
    on_arm do
      sha256 "e5779a4778f1ef15a89d646c0d709afcd56cbe678bdb86fce233651602eef225"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_arm64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
  end

  name "pmg"
  desc "PMG protects developers from malicious packages"
  homepage "https://github.com/safedep/pmg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmg"]
    end
  end

  # No zap stanza required

end
