# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmg" do
  version "0.17.2"

  on_macos do
    sha256 "a1e31730eef4b52c36a7ff2bec11e5f68724e1e3dcf78c6e74e17053981433c7"
    url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Darwin_all.tar.gz",
        verified: "github.com/safedep/pmg"
  end

  on_linux do
    on_intel do
      sha256 "9f6ad44445e1812859c7ed1e33c67a54dab2e6652e14f2327dc2336b9d09cf8c"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
    on_arm do
      sha256 "8012c7b3df6a135fb9cbd14d26e9fad4275cc2193a74bdf1015d85f01f3df695"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_arm64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
  end

  name "pmg"
  desc "PMG protects developers from malicious packages"
  homepage "https://github.com/safedep/pmg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmg"]
    end
  end

  # No zap stanza required

end
