# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmg" do
  version "1"

  on_macos do
    sha256 "ccc3495109f031a0c62948b40c2a4f1733d4943799d110d5aba77c04eb82a91e"
    url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Darwin_all.tar.gz",
        verified: "github.com/safedep/pmg"
  end

  on_linux do
    on_intel do
      sha256 "9c80370c7ed8cfe29e9b9ef70d1cbe1057c550143fdd7b56dbce55f06628ffaf"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
    on_arm do
      sha256 "1aa6b07df6fe6dcb5f8c9837d960f2079775511b507ba8d9a8de5028b33ad5b3"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_arm64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
  end

  name "pmg"
  desc "PMG protects developers from malicious packages"
  homepage "https://github.com/safedep/pmg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmg"]
    end
  end

  # No zap stanza required

end
