# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmg@edge" do
  version "0.28.0-edge.2"

  on_macos do
    sha256 "b759ba3e05db2683a9be7f513dd1199cbc84bcd1718228a1d496256d576e0f73"
    url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Darwin_all.tar.gz",
        verified: "github.com/safedep/pmg"
  end
  on_linux do
    on_arm do
      sha256 "bc4a554549e26537b759c7c16852c89fb4d25cc6f0c41e3a29d567414e8a3444"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_arm64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
    on_intel do
      sha256 "20a4a6f2212086929be73c53762038cd7090aec0afcea72d3ec1dc6e50c7a6c0"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
  end

  name "pmg@edge"
  desc "PMG protects developers from malicious packages"
  homepage "https://github.com/safedep/pmg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmg"]
    end
  end

  # No zap stanza required
end
