# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmg@edge" do
  version "0.28.0-edge.1"

  on_macos do
    sha256 "086c054a4a167f78b57011efb5d3279a11269c5d9be967e4770fb09379ed853d"
    url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Darwin_all.tar.gz",
        verified: "github.com/safedep/pmg"
  end
  on_linux do
    on_arm do
      sha256 "97b4fa3b9c52da167e42b47313ecddc1f0ee8871d104f7c418989708ddfe6ed7"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_arm64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
    on_intel do
      sha256 "7cb1570bce7e1c31f823bec97ae31401e3e10d3c8cbafe5508f538dce431c62b"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/pmg"
    end
  end

  name "pmg@edge"
  desc "PMG protects developers from malicious packages"
  homepage "https://github.com/safedep/pmg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmg"]
    end
  end

  # No zap stanza required
end
