# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmg@edge" do
  version "0.29.0-edge.3"

  on_macos do
    sha256 "91d96e1798fa5fc29e7e18b1c042cc88ef97e209f70a3236aad918a530df6188"
    url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "73abe0bedd732a967f7ca3e37a1baa943a39975aaec6508afe4ecc005b4a842f"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0684328c25072b02f9441981e77483dfc0e2c400f7a9f89b0fd575bfe40b0016"
      url "https://github.com/safedep/pmg/releases/download/v#{version}/pmg_Linux_x86_64.tar.gz"
    end
  end

  name "pmg@edge"
  desc "PMG protects developers from malicious packages"
  homepage "https://github.com/safedep/pmg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmg"]
    end
  end

  # No zap stanza required
end
