# This file was generated by GoReleaser. DO NOT EDIT.
cask "vet" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vet"], must_succeed: false
    end
  end

  version "1.20.0"

  on_macos do
    on_arm do
      sha256 "b4fa633b3fe15039f59ae9d9eefab8edf677c50cddd4e7785050a35950689c83"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf700952d726c73b524270b1d2151e48022c8ab67f88883d5010bc15b26e9ab7"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "764deb67ed4642f156e1384125e3709b098e5b8ef3330f83ba31b4836e890c4e"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb875389498d7a4cb6f0edda19ae18e976739a8f88187f994ccb8396e925569c"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_x86_64.tar.gz"
    end
  end

  name "vet"
  desc "SafeDep vet is a tool for identifying open source software supply chain risks"
  homepage "https://safedep.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vet"

  # No zap stanza required
end
