# This file was generated by GoReleaser. DO NOT EDIT.
cask "vet" do
  version "1.19.0"

  on_macos do
    on_arm do
      sha256 "4faa5eceedea1389c22f941979cc00208bdd8392986d05d539b769cadf2a36ad"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_arm64.tar.gz",
        verified: "github.com/safedep/vet"
    end
    on_intel do
      sha256 "8ecc2eb6670d2ee5f04c3afc5d95adecd08b63de3e118c42c1cc0adfd0454fe0"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_x86_64.tar.gz",
        verified: "github.com/safedep/vet"
    end
  end
  on_linux do
    on_arm do
      sha256 "0cf95eca4d79e9252e11f2a0d87e928a36efa3b417b853724eafa0b3748cf923"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_arm64.tar.gz",
        verified: "github.com/safedep/vet"
    end
    on_intel do
      sha256 "4e39ea7fb7c11e1edcdcf41a3c71766f62fb7f4533930b850afbd1bb441bb221"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/vet"
    end
  end

  name "vet"
  desc "SafeDep vet is a tool for identifying open source software supply chain risks"
  homepage "https://safedep.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vet"]
    end
  end

  # No zap stanza required
end
