# This file was generated by GoReleaser. DO NOT EDIT.
cask "vet" do
  version "1.18.2"

  on_macos do
    on_intel do
      sha256 "f8078a34813ea07fc6bfea24c56587a9680b2bd7d438c0b8d961f0e3531ab772"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_x86_64.tar.gz",
        verified: "github.com/safedep/vet"
    end
    on_arm do
      sha256 "9f824734ef322766ac8a66d1b4bdded1a916208534607c0d244a5c5f6fc508ca"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_arm64.tar.gz",
        verified: "github.com/safedep/vet"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d03948445be26bb318da5f0aea48d47605d2b099ad7aba2926b03f8d9a6103a"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_x86_64.tar.gz",
        verified: "github.com/safedep/vet"
    end
    on_arm do
      sha256 "f9786150bf12ffe299a44806b4c4f6dcb7c86017da0af8e32e8821a4f8ccb31f"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_arm64.tar.gz",
        verified: "github.com/safedep/vet"
    end
  end

  name "vet"
  desc "SafeDep vet is a tool for identifying open source software supply chain risks"
  homepage "https://safedep.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vet"]
    end
  end

  # No zap stanza required

end
