# This file was generated by GoReleaser. DO NOT EDIT.
cask "vet@edge" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vet"], must_succeed: false
    end
  end

  version "2.0.0-alpha.20261006112842"

  on_macos do
    sha256 "e7ea65f999f5ca0132b9938ec7f5291dbfaad60d6ccb18b8780f41525ab6e877"
    url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "f54be3212ab964902f289637cce3fd702bdbd1e7c00672b3f7b99c3a421a948b"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "14f183467ff448bf3ba476ae0326dea5bb5367268e58a3ff48b9e8afaa0d6f85"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_arm64.tar.gz"
    end
  end

  name "vet@edge"
  desc "SafeDep vet is a tool for identifying open source software supply chain risks"
  homepage "https://safedep.io"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "vet",
    ]

  binary "vet"

  # No zap stanza required

end
