# This file was generated by GoReleaser. DO NOT EDIT.
cask "vet@edge" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vet"], must_succeed: false
    end
  end

  version "2.0.0-alpha.20261006165446"

  on_macos do
    sha256 "5d57a1205fb613587e0ee89495059047816c789faa4b1f26466b7c0737cf3761"
    url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "34b18323c0566933103da7c54a880907759e1b04f38390000a73ac87c68dd117"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "02ed9c5c7dcea1db2915c45301009f8e5114e8939d20b9f6c5f1de5be0e4f0b0"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_arm64.tar.gz"
    end
  end

  name "vet@edge"
  desc "SafeDep vet is a tool for identifying open source software supply chain risks"
  homepage "https://safedep.io"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "vet",
    ]

  binary "vet"

  # No zap stanza required

end
