# This file was generated by GoReleaser. DO NOT EDIT.
cask "vet@edge" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vet"], must_succeed: false
    end
  end

  version "2.0.0-alpha.20261005063951"

  on_macos do
    sha256 "ba6eaed4815b47745a5da3f5cb33a9591ab01ed16258908e3d2509ae786ad91a"
    url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "789618182cb14ca5f07a62068a3e10a105e02e3c038fb69baf3a03720fb3ddd8"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4c431d22d02fa5f8a8a6e194aaacfc353eead42365396f6c02804d5992a0a077"
      url "https://github.com/safedep/vet/releases/download/v#{version}/vet_Linux_arm64.tar.gz"
    end
  end

  name "vet@edge"
  desc "SafeDep vet is a tool for identifying open source software supply chain risks"
  homepage "https://safedep.io"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "vet",
    ]

  binary "vet"

  # No zap stanza required

end
